const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const { mkdirSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

/**
 * Stops Android from copying this app's data off the device (UC-1.6a #150).
 *
 * `allowBackup="false"` alone is not enough on Android 12+. It turns off
 * cloud backup, but device-to-device transfer is a *separate* channel with its
 * own opt-out, and a value encrypted by the Android Keystore that arrives on a
 * new device cannot be decrypted there — so the user's restored app holds
 * unreadable credentials and behaves as if something is broken.
 *
 * `data_extraction_rules.xml` excludes every category from both channels.
 * There is nothing worth transferring: commitments live in Firestore under the
 * uid, and signing in on the new device is what brings them back.
 *
 * Written as a local plugin because `ios/` and `android/` are generated
 * (Continuous Native Generation): a hand-edited manifest would be overwritten
 * by the next prebuild.
 */

const RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDataExtractionRules.js — do not edit by hand. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </device-transfer>
</data-extraction-rules>
`;

/** Android 11 and below read this one; the newer file is ignored there. */
const LEGACY_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDataExtractionRules.js — do not edit by hand. -->
<full-backup-content>
    <exclude domain="root" />
    <exclude domain="file" />
    <exclude domain="database" />
    <exclude domain="sharedpref" />
    <exclude domain="external" />
</full-backup-content>
`;

function withRuleFiles(config) {
  return withDangerousMod(config, [
    'android',
    async modConfig => {
      const xmlDir = join(modConfig.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      mkdirSync(xmlDir, { recursive: true });
      writeFileSync(join(xmlDir, 'data_extraction_rules.xml'), RULES, 'utf8');
      writeFileSync(join(xmlDir, 'backup_rules.xml'), LEGACY_RULES, 'utf8');
      return modConfig;
    },
  ]);
}

function withManifestAttributes(config) {
  return withAndroidManifest(config, modConfig => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(modConfig.modResults);
    application.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';
    application.$['android:fullBackupContent'] = '@xml/backup_rules';
    // Belt and braces: `android.allowBackup` in app.config.ts sets this too,
    // and a release manifest that lost it would be a silent regression.
    application.$['android:allowBackup'] = 'false';
    return modConfig;
  });
}

module.exports = function withDataExtractionRules(config) {
  return withManifestAttributes(withRuleFiles(config));
};
