plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.maybesitter'
version = '1.0.0'

android {
  namespace 'expo.modules.healthconnectreadiness'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'androidx.health.connect:connect-client:1.1.0'
}
