/**
 * The runbook is held against the code, in both directions (#46).
 *
 * A runbook whose SLO table has drifted from the shipped definitions is worse
 * than no runbook: it is a document an on-call engineer will act on. So every
 * row here is parsed and compared against `SHADOW_SLO_CATALOG` field by field,
 * and — the direction that is usually skipped — every row in the document must
 * correspond to a shipped SLO, so a deleted definition leaves a failing test
 * rather than a stale row.
 *
 * The same both-directions rule is applied to the kill-switch stance table and
 * to the list of metrics that deliberately have no SLO.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { SHADOW_PIPELINE_CHAIN } from '../../src/contracts/v1/shadowPipelineContracts.ts';
import {
  SHADOW_SLO_CATALOG,
  SHADOW_SLO_METRIC_EXEMPTIONS,
} from '../../lib/operations/shadowSloCatalog.ts';
import { SHADOW_KILL_SWITCH_STANCE } from '../../lib/operations/shadowDrillPipeline.ts';
import { SHADOW_ROLLBACK_STEPS } from '../../lib/operations/shadowRollbackDrill.ts';

const RUNBOOK = readFileSync(
  path.join(process.cwd(), 'docs', 'operations', 'shadow-release-runbook.md'),
  'utf8',
);

function rows(): readonly string[][] {
  return RUNBOOK.split('\n')
    .filter((line) => line.indexOf('|') === 0)
    .map((line) =>
      line
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim().replace(/`/g, '')),
    );
}

function sloRows(): readonly string[][] {
  return rows().filter((cells) =>
    SHADOW_SLO_CATALOG.some((entry) => entry.definition.sloId === cells[0]),
  );
}

test('every shipped SLO has a runbook row, and every row is a shipped SLO', () => {
  const table = sloRows();
  assert.equal(table.length, SHADOW_SLO_CATALOG.length, 'the runbook table and the catalog differ in length');

  for (const entry of SHADOW_SLO_CATALOG) {
    const definition = entry.definition;
    const row = table.filter((cells) => cells[0] === definition.sloId)[0];
    assert.ok(row, `${definition.sloId} has no row in the runbook`);
    assert.deepEqual(
      row,
      [
        definition.sloId,
        entry.concern,
        definition.metric,
        definition.comparison,
        String(definition.threshold),
        definition.window,
        String(definition.minimumSampleCount),
        definition.owner.rotationId,
        definition.owner.escalationRotationId,
        definition.killSwitchModule === null ? '—' : definition.killSwitchModule,
      ],
      `${definition.sloId}: the runbook row disagrees with the shipped definition`,
    );
  }

  // The other direction: an sloId that appears in the document and nowhere else.
  const quoted = RUNBOOK.match(/`shadow-[a-z0-9-]+`/g) ?? [];
  for (const token of quoted) {
    const candidate = token.replace(/`/g, '');
    if (candidate.indexOf('shadow-oncall') === 0) continue;
    assert.ok(
      SHADOW_SLO_CATALOG.some((entry) => entry.definition.sloId === candidate),
      `the runbook names ${candidate}, which is not a shipped SLO`,
    );
  }
});

test('the runbook stance table matches the stance the sweep asserts', () => {
  for (const module of SHADOW_PIPELINE_CHAIN) {
    const row = rows().filter((cells) => cells[0] === module)[0];
    assert.ok(row, `${module} has no row in the kill-switch stance table`);
    assert.equal(row[1], SHADOW_KILL_SWITCH_STANCE[module], module);
    assert.equal(row[2], SHADOW_KILL_SWITCH_STANCE[module] === 'skipped_no_fallback' ? 'skipped' : 'fell_back', module);
    assert.equal(row[3], 'kill_switch_active', module);
  }
});

test('every metric without an SLO is named in the runbook with its reason', () => {
  for (const exemption of SHADOW_SLO_METRIC_EXEMPTIONS) {
    assert.ok(
      RUNBOOK.indexOf(exemption.metric) !== -1,
      `${exemption.metric} has no SLO and is not explained in the runbook`,
    );
  }
});

test('every rollback step the drill runs appears in the runbook sequence', () => {
  for (const stepId of SHADOW_ROLLBACK_STEPS) {
    assert.ok(RUNBOOK.indexOf(stepId) !== -1, `the runbook does not describe the step ${stepId}`);
  }
});

test('the runbook states the migration and rollback notes the issue asks for', () => {
  for (const heading of ['## 5. Migration and rollback notes', '## 6. What this does not cover']) {
    assert.ok(RUNBOOK.indexOf(heading) !== -1, `the runbook is missing "${heading}"`);
  }
});

test('the generated game-day report is not hand-editable without failing a test', () => {
  const report = readFileSync(
    path.join(process.cwd(), 'docs', 'operations', 'rollback-game-day-report.md'),
    'utf8',
  );
  assert.ok(report.indexOf('Generated by `renderShadowRollbackReport`') !== -1);
  assert.ok(report.indexOf('Do not edit by hand') !== -1);
});
